Start on expressions and statements, also featuring bodies and some connections between these elements
rust-marker/marker pull request #82
Opened 2023-01-06 21:34 UTC by xFrednet

This PR adds a basic statement, expression, and body representation to the API. With this, it's possible to represent simple literal expressions and more importantly, use `ExprKind` and `StmtKind` where needed. Merging this allows resolving several TODOs around the API as well as some parallelization.

This PR only includes the API frontend, the rustc backend will be added in a separate PR. As said, I'm not 100% happy with the rustc conversion code and want to focus on that part individually in a separate branch. Sadly, this means that this on its own is not testable. However, I trust rusts type system, and we can always adjust these structs later if needed.

---

@Niki4tap Would you like to review this? If you don't have the time, I'll merge this once the next step is ready, which will probably take a week or two.

2023-01-06 21:34 UTC, xFrednet commented
bors delegate=Niki4tap

2023-01-07 14:03 UTC, Niki4tap requested changes
Just comments, I don't think there is anything wrong with the code itself, mostly nits :)

2023-01-07 15:41 UTC, xFrednet commented on marker_api/src/ast/expr.rs
> +    /// Returns the span of this pattern.
Copy pasta got me again ^^ :spaghetti:

2023-01-07 15:42 UTC, xFrednet commented on marker_api/src/ast/expr/str_lit_expr.rs
> +    /// A normal standard string like `Hello \n world`
This was somewhat intentional, but I'll try to express it better

2023-01-07 15:45 UTC, xFrednet commented on marker_api/src/ast/expr/unstable_expr.rs
> +    /// this could represent different expressions with different precedents.
Not really :sweat_smile:

2023-01-07 15:50 UTC, xFrednet commented on marker_api/src/ast/expr/int_lit_expr.rs
> +    /// [`ExprData::ty`][`super::ExprData::ty`] method to determine the type,
The brackets have a different semantic meaning AFAIK. In markdown links can be expressed in two main ways:

```md
[Am animal that quacks](https://en.wikipedia.org/wiki/Duck)

<!-- Or -->

I like [ducks]!

[ducks]: https://en.wikipedia.org/wiki/Duck
```
---

[Am animal that quacks](https://en.wikipedia.org/wiki/Duck)

<!-- Or -->

I like [ducks]!

[ducks]: https://en.wikipedia.org/wiki/Duck

---

The `[name]` is an alias for an externally defined link. So this cases uses `[text][name]` to indicate that the text should be used for the link to `[name]`

2023-01-07 15:51 UTC, xFrednet commented on marker_api/src/ast/expr/float_lit_expr.rs
> +/// the written float literal or check for a range around the value in question.
Good point!

2023-01-07 16:07 UTC, xFrednet commented
Thank you for the review. Everything should be addressed now, though this I'll probably conflict with #72 now. I'll review that one the latest tomorrow :)

2023-01-07 16:39 UTC, Niki4tap commented
Thanks for addressing, looks good now!

bors r+

2023-01-07 16:45 UTC, merged

2023-01-07 18:05 UTC, xFrednet commented
Thank you for the review!